name: aoc_2025
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  args: ^2.7.0
  html: ^0.15.6
  http: ^1.6.0
  equatable: ^2.0.7

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  test: ^1.25.6
